### ISSUE TITLE
Creating a producer for UIApplication.applicationState causes a crash

### ISSUE THREAD

**Issue by rehatkathuria** [ReactiveCocoa/ReactiveSwift#738] opened 2019-05-29 09:02 UTC
Doing the following leads to a type cast crash on `NSObject+KeyValueObserving:152`.

```swift
UIApplication.shared.reactive
    .producer(for: \.applicationState)
    .observe(on: UIScheduler())
    .on(value: { foo in
        print("Handle \(foo) here.")
    })
    .start()
```

**Comment by rehatkathuria** [comment] 2019-05-29 09:03
Apologies, I should have included this in the original message. My dependencies are currently resolved to the following:

```
github "ReactiveCocoa/ReactiveCocoa" "10.0.0"
github "ReactiveCocoa/ReactiveSwift" "6.0.0"
```

**Comment by ikesyo** [comment] 2019-05-29 13:46
> `UIApplication.shared.reactive`

This should be filed in ReactiveCocoa, not ReactiveSwift, and this is a duplicate of https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3660.

**Closed by ikesyo** 2019-05-29 13:46 UTC
