### ISSUE TITLE
What happened to rac_textSignal?

### ISSUE THREAD

**Issue by emojiface** [ReactiveCocoa/ReactiveSwift#37] opened 2016-09-24 15:05 UTC
Hi, I'm porting a project using ReactiveCocoa to ReactiveSwift. I can't find rac_textSignal, what should be used instead?

**Comment by ikesyo** [comment] 2016-09-24 15:12
This is a duplicate of https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3197. See that issue for the details.

**Closed by ikesyo** 2016-09-24 15:12 UTC

**Comment by emojiface** [comment] 2016-09-25 15:24
Hey, @ikesyo, thanks for the response. I'm trying to add ReactiveObjC and ReactiveObjCBridge using CocoaPods, is this supported, or would I need to clone ReactiveSwift, add the two submodules, and drag into Xcode manually?
